---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: hemanth0409/javaproject:db
   ports:
     - "3306:3306"

 application:
   image: hemanth0409/javaproject:app
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
